name: 이슈 자동 담당자 지정

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assignAuthor:
    name: 이슈 작성자 담당자 지정
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 작성자 담당자 지정
        uses: technote-space/assign-author@v1
