name: FE 빌드 테스트

on: [pull_request]

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 노드 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: 의존성 설치
        run: pnpm install

      - name: 빌드 실행
        run: pnpm build
